# pipeline-run.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: metrics-app-pipeline-run-
spec:
  pipelineRef:
    name: metrics-app-pipeline
  serviceAccountName: pipeline
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/matej-ocovsky-metrics-app
    - name: image-repo
      value: image-registry.openshift-image-registry.svc:5000/matej-ocovsky-metrics-app-pipeline/metrics-app
  workspaces:
    - name: pfs-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
