apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  description: >-
    This task can be used to run npm goals on a project.

    This task can be used to run npm goals on a project where package.json is
    present and has some pre-defined npm scripts.
  params:
    - default: .
      description: The path where package.json of the project is defined.
      name: PATH_CONTEXT
      type: string
    - default:
        - version
      description: The npm goals you want to run.
      name: ARGS
      type: array
    - default: >-
        docker.io/library/node:12-alpine@sha256:12048cdfd75d944df35f3144132d9bdeee78015fbd6df765edad1be46599b110
      description: The node image you want to use.
      name: IMAGE
      type: string
  steps:
    - args:
        - $(params.ARGS)
      command:
        - npm
      env:
        - name: CI
          value: "true"
      image: $(params.IMAGE)
      name: npm-run
      resources: {}
      workingDir: $(workspaces.source.path)/$(params.PATH_CONTEXT)
  workspaces:
    - name: source
