apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger-template
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pfs-run-
      spec:
        pipelineRef:
          name: pfs-pipeline
        serviceAccountName: pipeline
        params:
          - name: source-repo
            value: https://github.com/matejocovskyibm/matej-ocovsky-metrics-app
          - name: image-repo
            value: image-registry.openshift-image-registry.svc:5000/matej-ocovsky-metrics-app-pipeline/metrics-app
        workspaces:
          - name: pfs-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
